spring:
  application:
    name: PublisherStart
  datasource:
    url: jdbc:postgresql://localhost:5432/publisher-start
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
